### ISSUE TITLE
Need help getting software up and running

### ISSUE THREAD

**Issue by therealjr** [DangerOnTheRanger/maniwani#145]
Can't find a simple way of making the server run on port 80. I searched every file for references to port 5000 and I changed it to 80. All it does then is fail to listen on any port. Is this because I'm not starting the server with admin privileges?

Secondly the themes are broken. It's just a simple white page, this is by default and I can't find a simple way of managing this.

**Comment by DangerOnTheRanger** [comment]
If you're using `docker-compose` or are otherwise going the production environment route, then you only need to remap the port that the nginx container receives from. Around [line 29](https://github.com/DangerOnTheRanger/maniwani/blob/master/docker-compose.yml#L29) in the stock `docker-compose.yml` change `"5000:5000"` (receive on port 5000 and forward to nginx's port 5000) to `"80:5000"` (receive on port 80 and forward to nginx's port 5000). You will probably need root privileges to bind to port 80, like you said.

If you're using the single-container setup as mentioned in the README (I definitely recommend it if you're just trying to test Maniwani out/work on it - is that your aim, or are you trying to make a public-facing deployment?) then instead of executing `docker run -p 5000:5000 maniwani-dev`, run `docker run -p 80:5000 maniwani-dev`. Again, you'll probably need root privileges.

Now with themes being broken: I'm going to assume you're using the production/multi-container environment option since that route's the most likely culprit for this problem; to me this indicates that static assets can't be fetched from your browser - try pulling up your browser's developer tools and see if there are any network request errors. It could be due to several factors:
1. Do you have an S3 server running? For smaller deployments you can probably get away with the file-and-folder storage backend. Have `SERVE_STATIC = True` and `STORAGE_PROVIDER = "FOLDER"` in your `maniwani.cfg` if you want to go the file-and-folder route.
2. Your S3 server is rejecting requests due to CORS - see this part of [deploying.md](https://github.com/DangerOnTheRanger/maniwani/blob/master/doc/deploying.md#configuring-your-production-environment) for how to fix that.
3. You're using the stock `docker-compose.yml` on a web server and trying to access it from an external machine. That file works great for simulating the production environment on an individual computer, but won't work across a network. I recommend reading through [deploying.md](https://github.com/DangerOnTheRanger/maniwani/blob/master/doc/deploying.md) for more info if this is the case.

**Comment by therealjr** [comment]
First of all thank you for your response! This is the nicest looking imageboard software I have come across which is why I've chosen it. I plan on adding more features to the software and I'll make sure to post code whenever I do so that others may expand upon it.

I modified docker-compose.yml and changed 5000:5000 to 80:5000 like you said. Then I started the server with root privileges but the server remains offline. I would like to report on the themes further but since I can't even get the server running on port 80 I won't be able to poke around. 

I am not running an s3 server. This is a simple vps running ubuntu 16.04 with docker installed.

**Comment by therealjr** [comment]
I'm currently in your IRC channel if we could discuss it there further. Idk what would be best for you.

**Comment by DangerOnTheRanger** [comment]
I'm closing this issue, since it got worked out in IRC - adding `SERVE_STATIC = True` and `STORAGE_PROVIDER = "FOLDER"` to `maniwani.cfg` and then restarting the container fixed the theme issue. Modifying the `docker-compose.yml` as well as the nginx config to move the listening port from 5000 to 80 fixed that issue, as well.
