### ISSUE TITLE
adding custom themes

### ISSUE THREAD

**Issue by therealjr** [DangerOnTheRanger/maniwani#171]
I created a custom theme's folder under scss/themes/mytheme which contains navbar.scss, post.scss, and theme-mytheme.scss. 
However when I try to find the theme in the drop-down selection I cannot find it. Is there something in addition to creating the additional theme files that I need to do?

**Comment by DangerOnTheRanger** [comment]
You'll need to add the name of your new theme to `THEME_LIST` in the configuration file. [deploying.md](https://github.com/DangerOnTheRanger/maniwani/blob/f8f850c6a1efb7d43589ee227caa8f2f70e9fc1f/doc/deploying.md#configuring-maniwani) goes into a little more detail. I think it's rather inefficient to have to do this kind of thing myself, so I'm very open to ideas on how to auto-discover themes instead of manually specifying which ones are available.

You also may want to pull from the [bootstrap-removal](https://github.com/DangerOnTheRanger/maniwani/tree/bootstrap-removal) branch if you're working on theming, since the CSS framework is undergoing a partial rewrite as per #163. You shouldn't have to change much, but enough will change that it might be a good idea to get started on it now, I think.

**Comment by therealjr** [comment]
Thanks for the input. I was planning on implementing some sort of management system for themes inside of the site admin page. I know I asked this before but is there a simpl(ish) way of editting/saving edits to static pages you serve in the site? That would allow me to complete what I have written for the site admin page so far. Then I could go onto themes.

**Comment by therealjr** [comment]
Could you join the irc channel? It would make some of my issues much easier to explain.

**Comment by DangerOnTheRanger** [comment]
By static pages, do you mean things like the FAQ? Those are still rendered with Jinja, so modifying the appropriate template in the `templates/` directory should work.

I can join IRC, yeah. I should be able to be online for about the next hour and a half.
