### ISSUE TITLE
Move away from Flask.

### ISSUE THREAD

**Issue by iamtheoneaboveall** [DangerOnTheRanger/maniwani#31]
https://www.techempower.com/benchmarks/#section=test&runid=2711d6a5-fbc0-4989-8606-8c532da9b088&hw=ph&test=plaintext&l=zijzen-3

This is on a 10 Gbit 14 core/28 threads server and flask can barely pull 90k requests/sec (plaintext "hello world") move away from it and use something like falcon.

**Comment by DangerOnTheRanger** [comment]
[Flask is used by a lot of places that are bigger than any Maniwani installation I foresee popping up in the near future](https://github.com/rochacbruno/flask-powered), if it's good enough for them it's probably good enough for us. Swapping out Flask would be a huge undertaking too, since most of Maniwani's dependencies are also Flask plugins; usage of Flask pretty much permeates the codebase. If you could submit a PR, though... ;)

I'd also point out that that benchmark is a little misleading if you're gonna try to use to as an example of production performance since most large production sites run on more than one server - horizontal scaling is pretty big in the web world.

**Comment by iamtheoneaboveall** [comment]
your "if X is using it i'll use it too" argument is enough for me not to contribute to this project. good luck!

**Comment by DangerOnTheRanger** [comment]
Thanks, appreciate the kind words!
