### ISSUE TITLE
Mosaic tiling of posts/threads

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#87]
Similar to Tumblr or Pinterest, would be used to save screen space.

**Comment by DangerOnTheRanger** [comment]
It's funny that you mention this; Maniwani used to render catalogs and the front page in such a manner, as you can see in the README that hasn't had updated screenshots in a little bit as well as on various older pictures floating around out there. It wasn't exactly too popular (the look of the catalog was probably the most common criticism of Maniwani at that point in time), and required Javascript to function as well - thus, in keeping with the stated promise in the README of being able to use Maniwani without needing Javascript, a separate flexbox-based catalog implementation had to be maintained for users without JS enabled.

I'm pretty happy with the way the current CSS grid-based catalog looks (especially considering it doesn't require that I maintain 2 different catalog rendering implementations and make sure they both work on desktop and mobile), but I wouldn't be opposed to bringing the old Pinterest look back in some form if there was demand for it, perhaps somehow integrating it with the old Futaba-based catalog view that a decent amount of people have been asking for, which would help justify bringing it back as well.

**Comment by DonaldTsang** [comment]
@DangerOnTheRanger I think there are ways of working around it using complete CSS.
- https://codepen.io/jacobg182/pen/YXQoJL
- https://codepen.io/brob/pen/zBmJRX

**Comment by DonaldTsang** [comment]
@DangerOnTheRanger I think there are ways of working around it using complete CSS.
- https://codepen.io/jacobg182/pen/YXQoJL
- https://codepen.io/brob/pen/zBmJRX

**Comment by DangerOnTheRanger** [comment]
The issue with those is that they require prior knowledge of how large each cell is in relation to one another; if you look at the source code for both, the size of each cell is manually set instead of being dynamically calculated. The problem with that is that approach would require calculating how much space a given thread would take up prior to rendering it, which is fairly difficult to do on the server.
Another problem becomes apparent once you resize the browser window on either of those examples - they just shrink further. This is not ideal behavior on smaller screens such as mobile devices where anything but one (maybe two) columns of catalog entries is too small to read.

CSS media queries can be used to figure out how large the user's screen is, but when you have a lot of relatively arbitrarily-sized tiles and need to rearrange them in a different number of rows and columns, the position in which they fit "best' (with little-to-no gap inbetween) changes. This is what masonry.js is for, and why JS is necessary for a responsive catalog.

**Comment by DonaldTsang** [comment]
Am currently reading these two articles
- https://medium.com/@mew/responsive-gallery-tiles-with-pure-css-b24e1ae5068
- https://w3bits.com/css-masonry/

**Comment by DangerOnTheRanger** [comment]
That's another large problem, yes. Theoretically you could rearrange the order of the thread thumbnails on the server to take that into account (so the first row still reads in chronological order), but that will quit working as soon as the grid resizes, since the columns will change lengths - and the first row will thus be composed of a different set of threads.

[This article](https://w3bits.com/css-grid-masonry/) by the same guy comes a bit closer, but the final solution doesn't work without Javascript.

**Comment by DangerOnTheRanger** [comment]
Closing this issue for now since there unfortunately doesn't seem to be a way to do mosaic tiling with pure CSS, and since the UI hasn't used the mosaic layout for about a year, as well.
