### ISSUE TITLE
DoS resistance

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#94]
Someone is DoSing your site with this script
Also https://www.youtube.com/watch?v=7wivOEXlL9s
```
#!/usr/bin/env bash
 
function test(){
  while :
  do
    curl -s  --output /dev/null https://futatsu.org/threads/370
  done
}
 
for i in {1..1000}
do
    test &
done
 
function cleanup(){
  pkill -P $$
}
 
trap cleanup EXIT
 
while :
  do
  sleep 1
done
```

**Comment by DangerOnTheRanger** [comment]
This should be handled by #92 and #93, but I appreciate the ticket.

**Comment by DonaldTsang** [comment]
@DangerOnTheRanger you forgot that flood-proofing could be an issue not solved by #92 and #93

**Comment by DangerOnTheRanger** [comment]
The way I see it, making Maniwani more resistant to DoS attacks is handled by doing two things:
1. Ensuring the codepath from client request > rendered HTML is as short as possible in the case of unchanged content. This is what I was referring to when I referenced #92 and #93, and there's still a little more work to be done on this front; ideally, rendered pages should be saved entirely within Redis and fetched from there if relevant content on them (posts, threads, etc.) have not changed. The way things are now, database results and rendered Markdown are cached, but templates are still re-rendered even if nothing has changed, which is the lion's share of the often >300ms response time on longer Futatsu threads. Returning rendered content directly from Redis should result in that response time being cut by about an order of magnitude or so.
2. Rate limiting in the case of many requests. I view this as the responsibility of whatever reverse proxy is placed in front of Maniwani - since that's something a reverse proxy is usually extremely good at - and not something the Maniwani codebase should directly handle. Properly setting rate limits is now a lot easier on S3-backed installations thanks to #93 being fixed, since a single request to a given URL on a Maniwani site should generate a single GET request to the application server, or two if live updating is enabled.

**Comment by DonaldTsang** [comment]
> I view this as the responsibility of whatever reverse proxy is placed in front of Maniwani - since that's something a reverse proxy is usually extremely good at - and not something the Maniwani codebase should directly handle.
People have voiced concern over certain reveres proxies (e.g. CloudFlare) being anti-privacy, and I can't really make a judgement on that. It would be best to have at least a very minimal rate limiter, for those who self-hosts the content.

**Comment by DangerOnTheRanger** [comment]
A reverse proxy doesn't have to necessarily be something like Cloudflare; it could be as simple as a single instance of nginx, which is actually the setup Futatsu uses at the moment. That kind of setup will take up negligible additional resources while still providing typical reverse proxy features - load balancing if you have additional backend servers, rate limiting, HTTPS support, etc. - which is the reason all the documentation for deploying Maniwani in production assumes use of at least nginx.

**Comment by DonaldTsang** [comment]
@DangerOnTheRanger in that case we should treat Nginx as part of the ManiWani "package" and state clearly that it does not require reverse proxies to operate.

**Comment by DangerOnTheRanger** [comment]
Using the example `docker-compose` setup found in this repo will automatically start nginx in front of Maniwani, and [deploying.md](https://github.com/DangerOnTheRanger/maniwani/blob/master/doc/deploying.md) also notes that a reverse proxy is recommended, but not strictly necessary. Unless you were referring to bundling nginx inside the Maniwani Docker image, which is not a practice I would recommend - it would prevent updating nginx independently of Maniwani and make custom nginx images/setups much harder, to say nothing of using an alternative reverse proxy.

**Comment by DonaldTsang** [comment]
@DangerOnTheRanger I meant using whatever means necessary to ship Nginx along side ManiWani without making installation harder, no matter docker image or not, to alleviate the need for 3rd party SaaS/IaaS "reverse proxies".

**Comment by DangerOnTheRanger** [comment]
Docker is about as easy as it will get to run nginx with Maniwani without somehow directly placing nginx itself in this repo somehow (which would be bad practice for the reasons I mentioned in my previous comment). `docker-compose` makes everything pretty turn-key; 4 terminal commands sourced from the README and you get Maniwani plus a full production-quality stack of nginx/redis/postgres/minio/captchouli. Customizing nginx further is something best left to the board admin since everyone's needs are different.

Deploying Maniwani without Docker is unsupported at the time in production environments, but it's not impossible. The documentation covers getting a Docker-less development environment up and running, and a decently-capable user should be able to take things from there.

I don't want to put something in the docs that I don't officially provide help and support for, and running a web application without containers is a major support headache that I'd rather not have to deal with by myself - specific packages on specific distros might not work, perhaps varying directory layouts cause issues, etc. Once the userbase picks up, or if another maintainer steps up to the plate, then we can see about official support for running Maniwani without Docker, but until then, that's extra effort I don't believe I can afford to expend.
